### PR TITLE
Update docs for provider support of optional configurations

### PR DESCRIPTION
**Pull request by taneyland**
*Issue #, if available:*

*Description of changes:*
Added a provider support matrix for optional configurations + update the supported optional configs on the provider-specific pages

*Testing (if applicable):*

*Documentation added/planned (if applicable):*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by vivek-koppuru — APPROVED** [review]
This is great!

**Review by chrisnegus — COMMENTED** [review]
/lgtm

**Review by drewvanstone — CHANGES_REQUESTED** [review]
I think all these relative links can be done with `[a relative link](other_file.md)` instead.

**Review by cxbrowne1207 — APPROVED** [review]

**Comment by g-gaston** [comment]
removing approve bc prow seems to be waiting for this PR and it won't merge until requested changes are resolved
@taneyland re-approve when you are ready

/remove-approve

**Comment by taneyland** [comment]
> I think all these relative links can be done with `[a relative link](other_file.md)` instead.

Talked to @chrisnegus on what's the recommended way to reference other pages. The reason we try to use relref or ref for internal references to the docs is because Hugo will test the link and fail to build the page if it does not exist. This helps us to avoid broken links.

**Comment by chrisnegus** [comment]
lgtm

**Pull request merged**
