### PR TITLE
fixed kube-vip yaml for nutanix provider

### PR DESCRIPTION
**Pull request by deepakm-ntnx**
*Issue #, if available:*

*Description of changes:*

*Testing (if applicable):*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by abhay-krishna** [comment]
@deepakm-ntnx The release tooling presubmit is failing because the bundle generation code for Nutanix ([bundles/nutanix.go](https://github.com/aws/eks-anywhere/blob/main/release/pkg/bundles/nutanix.go)) doesn't have the Kubevip field in the Nutanix struct, but that section is there in the golden file. So there's a mismatch when regenerating the bundle and checking it against the golden file. You just need to add the kube-vip field in nutanix.go like we do for vsphere(Lines [33](https://github.com/aws/eks-anywhere/blob/main/release/pkg/bundles/vsphere.go#L33) and [116](https://github.com/aws/eks-anywhere/blob/main/release/pkg/bundles/vsphere.go#L116))

**Review by abhinavmpandey08 — APPROVED** [review]
/approve
/woof

**Pull request merged**
