### PR TITLE
Update tinkerbell md and kubeadmconfig template names

### PR DESCRIPTION
**Pull request by ptrivedi**
* Update tinkerbell md template to accomodate mutable kubeadmconfigtemplate name

* Update tinkerbell md template names to have timestamps

*Issue #, if available:*

*Description of changes:*

*Testing (if applicable):*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by jaxesn** [comment]
I'm curious the use case this is solving? Mainly wondering if it's something that could apply more broadly across providers?

**Comment by ptrivedi** [comment]
> 

This change actually brings tinkerbell provider in consistency with others. vsphere and cloudstack already have these changes. I ran into the kubeadmconfigtemplate dynamic naming issue during debugging upgrade for bare metal when a hardcoded kubeadmconfigtemplate name was failing to apply during md rollout due to immutability reasons. As far as the timestamp for machine template name, that was added originally to vsphere/cloudstack to make these names unique to avoid conflict. To answer your question, this change really brings tinkerbell provider in sync with what other providers already had.

**Review by abhinavmpandey08 — APPROVED** [review]
/lgtm

**Pull request merged**
