### PR TITLE
bump prod cli release for 0.7.1

### PR DESCRIPTION
**Pull request by danbudris**
*Issue #, if available:*

*Description of changes:*
bump triggers for prod CLI release

*Testing (if applicable):*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by TerryHowe** [comment]
```
Manifest - projects/kubernetes-sigs/kind/latest/manifests/kindnetd.yaml
Error happened during retry after 1 retries: Requested object not found
```

not in download?

**Comment by abhay-krishna** [comment]
> ```
> Manifest - projects/kubernetes-sigs/kind/latest/manifests/kindnetd.yaml
> Error happened during retry after 1 retries: Requested object not found
> ```
> 
> not in download?

https://github.com/aws/eks-anywhere/pull/1310

this should resolve it.

**Pull request merged**
