### PR TITLE
Build eks-anywhere-packages during release.

### PR DESCRIPTION
**Pull request by ewollesen**
*Issue #, if available:*

*Description of changes:* Adding EKS-A Curated Packages components to the release.

*Testing (if applicable):*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by g-gaston — APPROVED** [review]

**Comment by TerryHowe** [comment]
tests are broken

**Comment by ewollesen** [comment]
> tests are broken

Fixed

**Review by abhay-krishna — APPROVED** [review]
/lgtm

**Pull request merged**
