### PR TITLE
Add upgrade examples for full lifecycle TF and Gitops

### PR DESCRIPTION
**Pull request by taneyland**
*Issue #, if available:*

*Description of changes:*

*Testing (if applicable):*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by csplinter** [comment]
Thank you for adding these examples for upgrading K8s minor versions. Can we add a comment to each section that the same method can be used to update other settings and configuration? That comment should link to [this section](https://anywhere.eks.amazonaws.com/docs/tasks/cluster/cluster-upgrades/vsphere-and-cloudstack-upgrades/#upgradeable-cluster-attributes) for vSphere, Nutanix, CloudStack, and Snow. It would also be good to understand what changes result in a rolling of the nodes, not sure if we have that documented.

**Review by chrisnegus — COMMENTED** [review]
/lgtm

**Review by chrisnegus — APPROVED** [review]
/lgtm

**Review by chrisnegus — APPROVED** [review]
/lgtm

**Pull request merged**
