### PR TITLE
Move /pkg/hardware to /pkg/providers/tinkerbell/hardware

### PR DESCRIPTION
**Pull request by chrisdoherty4**
Move `/pkg/hardware` to `/pkg/providers/tinkerbell/hardware`. The package represents interactions with the Tinkerbell hardware only.

### CODE REVIEW

**Comment by panktishah26** [comment]
Looks good to me. Can you please resolve the conflict?

**Comment by ptrivedi** [comment]
Thanks for this, it had been bothering me

**Pull request merged**
