### PR TITLE
Add namespace to controller install

### PR DESCRIPTION
**Pull request by TerryHowe**
Add namespace options to controller helm install

### CODE REVIEW

**Comment by TerryHowe** [comment]
/hold 

Wait for https://github.com/aws/eks-anywhere-packages/pull/506

**Comment by jonahjon** [comment]
What happens when you uninstall package controller, and try to re-install here?

**Comment by TerryHowe** [comment]
> What happens when you uninstall package controller, and try to re-install here?


It should work, but we need to use these options on install now.

**Pull request merged**
