### PR TITLE
Update docs site for release v0.8.0

### PR DESCRIPTION
**Pull request by danbudris**
*Issue #, if available:*

*Description of changes:*

*Testing (if applicable):*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by abhay-krishna — APPROVED** [review]
/lgtm

**Comment by vivek-koppuru** [comment]
We should merge this to main too right?

**Comment by vivek-koppuru** [comment]
I can update to main in this PR because I have the changes saved: https://github.com/aws/eks-anywhere/pull/1560

**Pull request merged**
