### PR TITLE
Remove TODO that is not going to happen

### PR DESCRIPTION
**Pull request by TerryHowe**
This TODO I think was done already.

### CODE REVIEW

**Comment by chrisdoherty4** [comment]
Should we be removing the `replace` directive and depending on a released thing if this is done?

**Comment by TerryHowe** [comment]
I had to dig through the past

https://github.com/aws/eks-anywhere/blob/v0.5.0/go.mod#L39:40

**Comment by TerryHowe** [comment]
Yeh, we aren't going to used the versioned module and if we have to, we can address that at that time, no need for a TODO. I generally don't like TODOs, they should be issues if they are issues.

**Pull request merged**
