### PR TITLE
Upgrade go version to 1.17

### PR DESCRIPTION
**Pull request by a-cool-train**
*Description of changes:*
Upgrading go version to 1.17 

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by a-cool-train** [comment]
> We need to make some build tooling changes I think to support the new version, so let's get that done too. Any other motivation to upgrade apart from staying up to date?

Yes, we are currently planning on integrating eks-a-packages and the package is currently using go 1.17 and this is causing some versioning concerns.

**Comment by abhay-krishna** [comment]
Was `go mod tidy` run after updating the go.mod file?

**Comment by jaxesn** [comment]
Youll need to bump [this](https://github.com/aws/eks-anywhere/blob/main/Makefile#L23).

**Comment by chrisdoherty4** [comment]
Why 1.17 when 1.18 released?

**Pull request closed without merging**
