### PR TITLE
Tinkerbell - changed stream image action timeout to 600

### PR DESCRIPTION
**Pull request by panktishah26**
*Description of changes:*
Increased stream-image action timeout to 600 from 360 to avoid timing out during machine provisioning.

### CODE REVIEW

**Comment by abhinavmpandey08** [comment]
isn't this already handled in https://github.com/aws/eks-anywhere/pull/2426?

**Comment by panktishah26** [comment]
> isn't this already handled in #2426?

I didn't notice Pooja's PR. As it just got merged I am closing this PR.

**Pull request closed without merging**
