### PR TITLE
IAM Authenticator for provider Tinkerbell

### PR DESCRIPTION
**Pull request by pokearu**
*Issue #2749*
Also addresses #2885 

*Description of changes:*
Changes to enable support for `aws-iam-authenticator` integration for EKS-A with provider tinkerbell.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by d8660091** [comment]
I see the test is doing ValidateAWSIamAuth(), but I am not sure if this line is invoked, https://github.com/d8660091/eks-anywhere/blob/snow-machine-config-validate-in-reconciler/pkg/clusterapi/apibuilder.go#L205, without it, the iam authenticator would not work correctly, right?

**Comment by pokearu** [comment]
> I see the test is doing ValidateAWSIamAuth(), but I am not sure if this line is invoked, https://github.com/d8660091/eks-anywhere/blob/snow-machine-config-validate-in-reconciler/pkg/clusterapi/apibuilder.go#L205, without it, the iam authenticator would not work correctly, right?

I am actually not sure. Let me check. Right now all the e2e tests for IAM Auth invoke that validate.

**Pull request merged**
