### PR TITLE
Remove snow machine objects exist check in controller

### PR DESCRIPTION
**Pull request by jiayiwang7**
*Issue #, if available:*

Change #3795 

*Description of changes:*

We already check the machine config existence in controller here: https://github.com/aws/eks-anywhere/blob/main/pkg/cluster/snow.go#L157-L160.

*Testing (if applicable):*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by taneyland** [comment]
Do we still need it here? https://github.com/aws/eks-anywhere/blob/main/pkg/cluster/snow.go#L74

**Comment by jiayiwang7** [comment]
> Do we still need it here? https://github.com/aws/eks-anywhere/blob/main/pkg/cluster/snow.go#L74

yea we need it for cli validation since cli does not build spec from cluster

**Pull request merged**
