### PR TITLE
Add terminal UI to display analyzer results

### PR DESCRIPTION
**Pull request by YoyoTT**
enecccbnikegunfhjnherlnekglgvuleuueirbbvvcld
*Issue #, if available:*

*Description of changes:*

Reference to [Troubleshoot.sh](https://github.com/replicatedhq/troubleshoot/blob/main/cmd/troubleshoot/cli/interactive_results.go) and termui, add a terminal UI to display analyzer outputs.
The UI will be automatically presented with list of analyzer outputs when executing support bundle by running command `eksctl anywhere generate support-bundl -f cluster.yaml`. 

*Testing (if applicable):*

run command `./bin/eksctl anywhere generate support bundle -f cluster.yaml` to invoke the support bundle generation. Once it's done, the analyzer outputs are displayed as:
image (1)

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by danbudris** [comment]
@YoyoTT could you add some information about how this PR was tested?

**Comment by YoyoTT** [comment]
> @YoyoTT could you add some information about how this PR was tested?

Yeah, but I'm suffering to seek a better way to test it. Once I figured it out, I'll update the above info box. Currently, I test it by running `./bin/eksctl anywhere generate support bundle -f cluster.yaml`, then the table will be printed out correctly.

**Comment by mitalipaygude** [comment]
> > @YoyoTT could you add some information about how this PR was tested?
> 
> Yeah, but I'm suffering from seeking a better way to test it. Once I figured it out, I'll update the above info box. Currently, I test it by running `./bin/eksctl anywhere generate support bundle -f cluster.yaml`, then the table will be printed out correctly.

Can you take a screenshot and upload it for the pr maybe?

**Comment by YoyoTT** [comment]
> > > @YoyoTT could you add some information about how this PR was tested?
> > 
> > 
> > Yeah, but I'm suffering from seeking a better way to test it. Once I figured it out, I'll update the above info box. Currently, I test it by running `./bin/eksctl anywhere generate support bundle -f cluster.yaml`, then the table will be printed out correctly.
> 
> Can you take a screenshot and upload it for the pr maybe?

Yeah, sure!

**Comment by danbudris** [comment]
since we're re-purposing code from troubleshoot.sh to implement a similar UI, we need to make sure to supply an attribution in `analyzer_output_ui.go`. 

An example of an attribution can be found here: https://github.com/aws/eks-anywhere-build-tooling/blob/main/build/lib/cherry_pick_pull.sh#L4

this outlines the original source, their license, and then the modifications that we've made.

The alternative to this is to import the necessary packages and just directly use them. The last time I tried to import TS into EKS-A there were some thorny issue with their go mod that prevented me from doing it successfully; I don't know if they've resolved that, but it would be ideal if we could just import them and call these methods directly.

**Review by g-gaston — COMMENTED** [review]
Before merging this, I think we need a plan on how we are going to test this :)
We can take the conversation offline and update the PR with the plan

**Comment by mitalipaygude** [comment]
Will be discussed after offline discussion and updated here https://github.com/aws/eks-anywhere/issues/3628

**Pull request closed without merging**
