### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by ptrivedi**
*Issue #, if available:*

*Description of changes:*

*Testing (if applicable):*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by pokearu — APPROVED** [review]

**Review by abhinavmpandey08 — APPROVED** [review]
/approve
/lgtm
/woof

**Comment by ptrivedi** [comment]
and

/roar

**Comment by ptrivedi** [comment]
fine, whatever, 
/baa

**Comment by abhinavmpandey08** [comment]
image

**Pull request merged**
