### PR TITLE
Remove feature flag for 1.24

### PR DESCRIPTION
**Pull request by mitalipaygude**
*Issue #, if available:*
#3491 
*Description of changes:*
[Remove feature flag for 1.24](https://github.com/aws/eks-anywhere/commit/c440dda22f8d5380b6976261cd10eb486a990f68)
*Testing (if applicable):*
- make
- make e2e

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by TerryHowe — APPROVED** [review]
/lgtm

Where is the default kubeVersion pulled from, the bundle?

**Comment by mitalipaygude** [comment]
Changing the default kube version is from the cluster.go file. Will send out a pr for that.

**Review by vivek-koppuru — APPROVED** [review]

**Pull request merged**
