### PR TITLE
Add Gloo Edge, and Gloo Mesh.

### PR DESCRIPTION
**Pull request by murphye**
Solo.io is an EKS anywhere partner.

https://aws.amazon.com/eks/eks-anywhere/partners/

*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by abhay-krishna** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/aws/eks-anywhere/pull/373#" title="Author self-approved">murphye</a>*
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **chrisnegus**
You can assign the PR to them by writing `/assign @chrisnegus` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=aws%2Feks-anywhere).

<details open>
Needs approval from an approver in each of these files:

- **[docs/OWNERS](https://github.com/aws/eks-anywhere/blob/main/docs/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by abhay-krishna** [comment]
Hi @murphye. Thanks for your PR.

I'm waiting for a [aws](https://github.com/orgs/aws/people) member to verify that this patch is reasonable to test. If it is, they should reply with `/ok-to-test` on its own line. Until that is done, I will not automatically test new commits in this PR, but the usual testing commands by org members will still work. Regular contributors should [join the org](https://github.com/orgs/aws/people) to skip this step.

Once the patch is verified, the new status will be reflected by the `ok-to-test` label.

I understand the commands that are listed [here](https://go.k8s.io/bot-commands?repo=aws%2Feks-anywhere).

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by jaxesn** [comment]
Holding this while we discuss internally the best place in the docs to include partner integrations.

/hold

**Comment by chrisnegus** [comment]
Solo.io is an EKS-A partner, so it meets the criteria for inclusion here.
/lgtm

**Comment by chrisnegus** [comment]
@murphye We will be adding a docs contributor page to provide guidelines. In the mean time, this meets the criteria we discussed. Thanks for the PR and sorry it took so long to approve.

**Comment by g-gaston** [comment]
I think this needs a rebase
If not one is on it, I can help

**Pull request merged**
