### PR TITLE
Adding packages smoke tests for k8s version 1.24

### PR DESCRIPTION
**Pull request by junshun**
Adding simple flow test for packages with providers: Docker, vSphere Ubuntu, and vSphere BottleRocket

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by ivyostosh** [comment]
Are we still supporting 1.20 with the release on 1.24? Can we remove the 1.20 tests?

**Comment by jonahjon** [comment]
> Are we still supporting 1.20 with the release on 1.24? Can we remove the 1.20 tests?

We can remove them on 12/15

**Pull request merged**
