### PR TITLE
Add static ip setup for Bottlerocket:

### PR DESCRIPTION
**Pull request by jacobweinstock**
*Issue #, if available:*

*Description of changes:*
This sets Bottlerocket up with feature parity with non Bottlerocket OS's. Static IP setting adds some reliability around DHCP.

Works in conjunction with https://github.com/aws/eks-anywhere-build-tooling/pull/1644

*Testing (if applicable):*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by chrisnegus — COMMENTED** [review]
@jacobweinstock Should we add anything to the docs for this change?

**Comment by jacobweinstock** [comment]
> @jacobweinstock Should we add anything to the docs for this change?

Hey @chrisnegus, I don't think it's necessary. This doesn't change anything from a customer perspective, in my opinion.

**Comment by jacobweinstock** [comment]
Hey @vignesh-goutham , mind reviewing this one?

**Review by vignesh-goutham — APPROVED** [review]

**Comment by jacobweinstock** [comment]
Hey @chrisnegus , I was wrong. Vignesh pointed out to me that we should update the [Bottlerocket TinkerbellTemplateConfig example](https://anywhere.eks.amazonaws.com/docs/reference/clusterspec/baremetal/#bottlerocket-tinkerbelltemplateconfig-example). Let me get a PR open and I will tag you. Thanks!

**Pull request merged**
