### PR TITLE
Remove repetitive vsphere reconciler tests

### PR DESCRIPTION
**Pull request by taneyland**
*Issue #, if available:*

*Description of changes:*
We now test these cases in `vsphere/reconciler/reconciler_test.go`. 

*Testing (if applicable):*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by g-gaston — APPROVED** [review]
What are the rest of the tests testing? The ones we are keeping in this file

**Comment by taneyland** [comment]
> What are the rest of the tests testing? The ones we are keeping in this file

We currently ignore self-managed clusters in the new controller, so we have one test for that. 
We are also testing the `reconcileDelete()` logic in this file. This happens in `cluster_controller.go`, outside of provider-specific reconcilers

**Comment by g-gaston** [comment]
> > What are the rest of the tests testing? The ones we are keeping in this file
> 
> We currently ignore self-managed clusters in the new controller, so we have one test for that. We are also testing the `reconcileDelete()` logic in this file. This happens in `cluster_controller.go`, outside of provider-specific reconcilers

Sounds good! could we move to `controllers_test` package?

**Review by g-gaston — COMMENTED** [review]
/lgtm

**Pull request merged**
