### PR TITLE
Adding quotes for datacenter field

### PR DESCRIPTION
**Pull request by adonskoy**
*Issue #, if available:* [#3381](https://github.com/aws/eks-anywhere/issues/3381)

*Description of changes:*
Added quotes to the `spec.template.spec.datacenter` value in VSphereMachineTemplate to ensure that the value type is always a string.

*Testing (if applicable):*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by TerryHowe — COMMENTED** [review]
/ok-to-test

**Comment by TerryHowe** [comment]
uugn, I could see one or two test failures, but way too many dependencies on that.

**Comment by adonskoy** [comment]
> This is a great find, thank you for sharing this! Now my question is, should we do this for the other string values in this file as well if they can support only integers as well?

As far as I can see, other values cannot be integers in this file, because they will either initially be a string, or are the result of concatenating other strings (for example, datastore)

**Comment by vivek-koppuru** [comment]
> > This is a great find, thank you for sharing this! Now my question is, should we do this for the other string values in this file as well if they can support only integers as well?
> 
> As far as I can see, other values cannot be integers in this file, because they will either initially be a string, or are the result of concatenating other strings (for example, datastore)

Good point, I think these changes are good then!

**Review by vivek-koppuru — APPROVED** [review]
/approve

**Comment by vivek-koppuru** [comment]
@adonskoy Can you rebase the changes in your branch and add this change to the `expected_results_minimal_autoscaling_md.yaml` file in the vsphere package as well? Seems to be a new test file

**Review by vivek-koppuru — APPROVED** [review]

**Comment by vivek-koppuru** [comment]
@adonskoy Thank you so much for your contribution!

**Pull request merged**
