### PR TITLE
Update tag to consume bug fix for clusterresourceset

### PR DESCRIPTION
**Pull request by vivek-koppuru**
*Issue #, if available:*

*Description of changes:*
Consume the tag that points to https://github.com/abhay-krishna/cluster-api/pull/6

(This got resolved, was an upstream Go issue) In order to get `go mod tidy` to work, I also needed to set `GOPRIVATE=github.com/abhay-krishna/cluster-api`

*Testing (if applicable):*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by vivek-koppuru** [comment]
/approve
/release-0.13

**Comment by vivek-koppuru** [comment]
Looks like the `GOPRIVATE` export I did locally might be needed for athens too, but not sure if there is just a propagation delay until the tag gets ready.

**Comment by vivek-koppuru** [comment]
I see someone else has filed a ticket for a somewhat similar issue, curious what they are going to respond with: https://github.com/golang/go/issues/57185

**Comment by g-gaston** [comment]
/lgtm
However, if the module is giving problems, we don't need this to be merged just yet, so no rush. The change was only in the crs code, which the cli doesn't depend on directly

**Comment by vivek-koppuru** [comment]
Seems to have been an issue on the golang upstream servers side. Looks like the issue is resolved now

**Pull request merged**
