### PR TITLE
Patch containerd to v1.6.19 in release module

### PR DESCRIPTION
**Pull request by chrisdoherty4**

### CODE REVIEW

**Review by TerryHowe — APPROVED** [review]
/lgtm

**Comment by TerryHowe** [comment]
The other pr merged, so maybe...

**Review by g-gaston — APPROVED** [review]

**Comment by chrisdoherty4** [comment]
Awaiting https://github.com/aws/eks-anywhere/pull/5169 that we think should fix the tests.

**Comment by TerryHowe** [comment]
Can you just run `make update-bundle-golden-files` and include that

**Comment by chrisdoherty4** [comment]
> Can you just run `make update-bundle-golden-files` and include that

CI running with the change now. Thanks.

**Pull request merged**
