### PR TITLE
Re-add driver and syncer components to bundle

### PR DESCRIPTION
**Pull request by abhay-krishna**
Adding back the vSphere CSI driver and syncer images back to the bundle.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by g-gaston — APPROVED** [review]

**Comment by abhay-krishna** [comment]
/override eks-anywhere-release-tooling-presubmit
known failure because cert-manager hasn't built yet.

**Pull request merged**
