### PR TITLE
Add test to validate generated tinkerbell manifests for upgrade with cert bundles

### PR DESCRIPTION
**Pull request by HiteshRepo**
Verifies [6095](https://github.com/aws/eks-anywhere/pull/6095)  for cert bundles in `TinkerbellMachineTemplate` manifest.

The issue [6108](https://github.com/aws/eks-anywhere/issues/6108) was also happening due to same incorrect way of splitting yaml as mentioned in PR [6095](https://github.com/aws/eks-anywhere/pull/6095) and the #6095 PR helped fixing the same. 

This PR validates the same fix for cert bundles config as well.

### CODE REVIEW

**Comment by HiteshRepo** [comment]
@chrisdoherty4 can we merge this?

**Review by chrisdoherty4 — APPROVED** [review]

**Pull request merged**
