### PR TITLE
Update Nutanix provider support details for unstacked etcd topology

### PR DESCRIPTION
**Pull request by yannickstruyf3**
*Issue #, if available:*
N/A

*Description of changes:*
Adding Nutanix as supported platform for unstacked etcd topology 

*Testing (if applicable):*
N/A

*Documentation added/planned (if applicable):*
Adding Nutanix as supported platform for unstacked etcd topology. 

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by taneyland** [comment]
Thanks for updating this! Can we also update [this page](https://anywhere.eks.amazonaws.com/docs/getting-started/nutanix/nutanix-spec/#cluster-fields) to show that the `externalEtcdConfiguration` fields are available with Nutanix now?

Something like [this ](https://anywhere.eks.amazonaws.com/docs/getting-started/vsphere/vsphere-spec/#externaletcdconfigurationcount)

**Comment by yannickstruyf3** [comment]
@taneyland Thanks for your feedback. Updated the page.

**Review by taneyland — APPROVED** [review]

**Pull request merged**
