### PR TITLE
Clarify Cluster Autosclaer Deployment Topologies

### PR DESCRIPTION
**Pull request by jonathanmeier5**
*Issue #, if available:*

*Description of changes:*

*Testing (if applicable):*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by TerryHowe — APPROVED** [review]
/lgtm
/approve

**Comment by TerryHowe** [comment]
cherry pick?

**Comment by jonathanmeier5** [comment]
> cherry pick?

@TerryHowe I should have put a hold/wip on this, my bad. Let's hold off on cherry pick. I've been loaned out to another project on short notice and haven't had time to finalize this. Will try to do so Monday.

**Pull request merged**
