### PR TITLE
Update e2e instance count

### PR DESCRIPTION
**Pull request by taneyland**
*Issue #, if available:*

*Description of changes:*

*Testing (if applicable):*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by mitalipaygude** [comment]
We are increasing the count by 50? is this due to the timeout for e2e tests? was it caused by lack of resources?

**Comment by taneyland** [comment]
> We are increasing the count by 50? is this due to the timeout for e2e tests? was it caused by lack of resources?

They're testing that out now. I think the e2e test issues are likely a matter of cleaning up resources. 
However, our current instance count is 217, which is why I increased it to 220.

**Comment by TerryHowe** [comment]
> > We are increasing the count by 50? is this due to the timeout for e2e tests? was it caused by lack of resources?
> 
> They're testing that out now. I think the e2e test issues are likely a matter of cleaning up resources. However, our current instance count is 217, which is why I increased it to 220.


If current instance count is 217 and this changes the value from 170 to 220, what does this change do?

**Comment by taneyland** [comment]
I now remember that the count in our e2e channel is the count of actual tests that failed, not the instance count because many of those tests are actually running on the same instance.So I'm going to close this PR. As folks look into the tests more, we can increase this as needed

**Pull request closed without merging**
