### PR TITLE
Added list of firewall ports for EKS-A

### PR DESCRIPTION
**Pull request by chrisnegus**
*Issue #, if available:*

Created a list of ports that need to be open in for EKS-A. This is per a customer request.

### CODE REVIEW

**Comment by abhay-krishna** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/aws/eks-anywhere/pull/536#" title="Author self-approved">chrisnegus</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=aws%2Feks-anywhere).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[docs/OWNERS](https://github.com/aws/eks-anywhere/blob/main/docs/OWNERS)~~ [chrisnegus]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by abhinavmpandey08 — COMMENTED** [review]
Should also mention port 22, which is open for ssh on control plane, worker and etcd nodes

**Comment by chrisnegus** [comment]
> Should also mention port 22, which is open for ssh on control plane, worker and etcd nodes
Done.

**Review by abhinavmpandey08 — APPROVED** [review]

**Comment by abhay-krishna** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/aws/eks-anywhere/pull/536#pullrequestreview-795893631" title="Approved">abhinavmpandey08</a>*, *<a href="https://github.com/aws/eks-anywhere/pull/536#" title="Author self-approved">chrisnegus</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=aws%2Feks-anywhere).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[docs/OWNERS](https://github.com/aws/eks-anywhere/blob/main/docs/OWNERS)~~ [abhinavmpandey08,chrisnegus]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by rothgar** [comment]
Doesn't have to be in this PR but we may also want to link to outbound ports (eg service ranges for kube-proxy) and maybe link to the FAQ about what hosts are used to download EKS-A bits.

**Pull request merged**
