### PR TITLE
Update docs to point to latest OVAs

### PR DESCRIPTION
**Pull request by abhay-krishna**
Update artifacts section in docs to reference the newly-generated OVAs for Ubuntu, along with EKS-D release tags on vCenter.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by abhay-krishna** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/aws/eks-anywhere/pull/379#" title="Author self-approved">abhay-krishna</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=aws%2Feks-anywhere).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[docs/OWNERS](https://github.com/aws/eks-anywhere/blob/main/docs/OWNERS)~~ [abhay-krishna]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by pokearu — APPROVED** [review]

**Comment by abhay-krishna** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/aws/eks-anywhere/pull/379#" title="Author self-approved">abhay-krishna</a>*, *<a href="https://github.com/aws/eks-anywhere/pull/379#pullrequestreview-770864741" title="Approved">pokearu</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=aws%2Feks-anywhere).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[docs/OWNERS](https://github.com/aws/eks-anywhere/blob/main/docs/OWNERS)~~ [abhay-krishna,pokearu]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by TerryHowe** [comment]
Is the current build of the CLI going to pull these? In theory, we should be able to pull the latest bundle in case there are important security fixes

**Comment by chrisnegus** [comment]
Would it make sense to set up attributes for release version numbers that could be read into the OVA names automatically? It may not be a big deal, since all the artifacts seem to be in one file now. But as the project grows, there may be more places where the version number might be needed.

**Review by vignesh-goutham — APPROVED** [review]
/lgtm

**Pull request merged**
