### PR TITLE
Metallb 0.13.7 docs

### PR DESCRIPTION
**Pull request by lewisdiamond**
Can be viewed here: https://docs.dx3ehyyttf163.amplifyapp.com/docs/reference/packagespec/metallb/

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by jonahjon** [comment]
Can you change `docs/content/en/docs/reference/packagespec/_index.md` to point to the new version

**Review by chrisnegus — APPROVED** [review]
/lgtm

**Pull request merged**
