### PR TITLE
Update validated hardware list

### PR DESCRIPTION
**Pull request by ndeksa**
*Issue #, if available:*
NA
*Description of changes:*
Modified validated hardware list
*Testing (if applicable):*
NA
*Documentation added/planned (if applicable):*
Modified EKS-A BM qualified hardware list

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by csplinter** [comment]
lgtm

**Review by csplinter — APPROVED** [review]

**Review by chrisnegus — APPROVED** [review]
/lgtm

**Pull request merged**
