### PR TITLE
removed feature is active checks for nutanix provider

### PR DESCRIPTION
**Pull request by deepakm-ntnx**
*Issue #, if available:*

*Description of changes:*
This is given as we want to go GA without setting the feature flag

*Testing (if applicable):*
TODO

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by pokearu** [comment]
@deepakm-ntnx Looks like we might need to remove the `"github.com/aws/eks-anywhere/pkg/features"` import from some of the files under `test/e2e`. 
Could we try running `make e2e` it should display the errors locally.

**Comment by deepakm-ntnx** [comment]
> @deepakm-ntnx Looks like we might need to remove the `"github.com/aws/eks-anywhere/pkg/features"` import from some of the files under `test/e2e`. Could we try running `make e2e` it should display the errors locally.

Thanks, this helped. pushed the fix. was looking at the wrong log in prow.

**Comment by pokearu** [comment]
Could we also remove the feature gate function and the variable
https://github.com/aws/eks-anywhere/blob/main/pkg/features/features.go#L59

If we do not plan on using it again?

**Comment by deepakm-ntnx** [comment]
> Could we also remove the feature gate function and the variable https://github.com/aws/eks-anywhere/blob/main/pkg/features/features.go#L59
> 
> If we do not plan on using it again?

would you recommend using the same or a specific feature name based such function for say a feature which we don't want to enable yet.

**Comment by chrisdoherty4** [comment]
> > Could we also remove the feature gate function and the variable [`main`/pkg/features/features.go#L59](https://github.com/aws/eks-anywhere/blob/main/pkg/features/features.go?rgh-link-date=2022-11-23T23%3A41%3A14Z#L59)
> > If we do not plan on using it again?
> 
> would you recommend using the same or a specific feature name based such function for say a feature which we don't want to enable yet.

Each feature should really have its own flag so they can be released independently. Re-using this one could be misleading.

**Comment by abhinavmpandey08** [comment]
/hold
Let's hold this until the official release

**Review by abhinavmpandey08 — APPROVED** [review]
looks good! We will merge this once we are closer to Nutanix GA

**Review by abhinavmpandey08 — APPROVED** [review]
/approve
/lgtm

**Pull request merged**
