### PR TITLE
Add tinkerbell-chart to the bundle

### PR DESCRIPTION
**Pull request by abhinavmpandey08**
*Description of changes:*
This PR adds the `tinkerbell-chart` to the bundle

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by ptrivedi** [comment]
Would be good to have “tinkerbell-chart” as a const declaration. But I guess that applies to all other projects.

onky other thing is the arch being limited to amd64, but I guess it’s okay for now

**Comment by abhinavmpandey08** [comment]
> Would be good to have “tinkerbell-chart” as a const declaration. But I guess that applies to all other projects.
> 
> onky other thing is the arch being limited to amd64, but I guess it’s okay for now

We only build amd64 images. Also, the image arch doesn't matter too much since it's a helm chart and not a docker image

**Pull request merged**
