### PR TITLE
Remove method from provider reconciler interface

### PR DESCRIPTION
**Pull request by g-gaston**
*Description of changes:*
This method won't be needed and not used anywhere.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by chrisdoherty4** [comment]
Aren't there a bunch of implementations around this? How is CNI reconciled now?

**Review by cxbrowne1207 — APPROVED** [review]

**Comment by g-gaston** [comment]
> Aren't there a bunch of implementations around this? How is CNI reconciled now?

There aren't, there are no consumers for this method from the interface. It just happens that all the current implementations of this interface also implement the `ReconcileCNI` method, but that's not required.

CNI reconciliation is supposed to be part of the responsibilities of the `Reconcile` implementation of this interface. For reference, the actual reconciliation logic is in the `CNIReconciler` and the existing implementations of `ProviderClusterReconciler` get the `CNIReconciler` injected as a dependency.

**Review by mitalipaygude — APPROVED** [review]

**Pull request merged**
