### PR TITLE
Security Improvement for binary install

### PR DESCRIPTION
**Pull request by jaradtke-aws**
*Issue #, if available:*
The method for installing the eksctl and associated commands is not secure as it creates a file in a system-wide directory owned by a user (user = whoever the person is logged in as).  

*Description of changes:*
Instead of using mv (and chmod in some of the examples), use the "install" command with appropriate flags
ex - replace first line (mv) with the second (install)

```
sudo mv /tmp/eksctl /usr/local/bin/
sudo install -m 0755 /tmp/eksctl /usr/local/bin/eksctl
```

*Testing (if applicable):*

RHEL8
```
[jradtke@rhel8 ~]$ touch /tmp/test
[jradtke@rhel8 ~]$ ls -l /tmp/test
-rw-rw-r--. 1 jradtke jradtke 0 Apr 24 16:48 /tmp/test
[jradtke@rhel8 ~]$ sudo install -m 0755 /tmp/test /tmp/test1
[jradtke@rhel8 ~]$ ls -l /tmp | grep test
-rw-rw-r--. 1 jradtke jradtke  0 Apr 24 16:48 test
-rwxr-xr-x. 1 root    root     0 Apr 24 16:48 test1
```
macOS
```
macOS:~ jaradtke$ touch /tmp/test
macOS:~ jaradtke$ ls -l /tmp/test
-rw-r--r--  1 jaradtke  wheel  0 Apr 24 17:02 /tmp/test
macOS:~ jaradtke$ sudo install -m 0755 /tmp/test /tmp/test1
macOS:~ jaradtke$ ls -l /tmp/ | grep test
-rw-r--r--  1 jaradtke  wheel      0 Apr 24 17:02 test
-rwxr-xr-x  1 root      wheel      0 Apr 24 17:03 test1
macOS:~ jaradtke$ uname -s
Darwin
```
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by TerryHowe — COMMENTED** [review]
What environments was this tested on?

**Review by TerryHowe — APPROVED** [review]
/ok-to-test
/lgtm

**Comment by abhay-krishna** [comment]
/override eks-anywhere-e2e-validate-tinkerbell-hardware-presubmit

**Review by vivek-koppuru — APPROVED** [review]

**Review by drewvanstone — APPROVED** [review]

**Pull request merged**
