### PR TITLE
Adding Irsa to the workshop

### PR DESCRIPTION
**Pull request by gobrial**
*Issue #, if available:*

*Description of changes:*

*Testing (if applicable):*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by chrisnegus — COMMENTED** [review]
/lgtm

**Comment by TerryHowe** [comment]
Maybe make the docsy upgrade in another PR if that is required

**Comment by TerryHowe** [comment]
images missing
```
docs/workshops/iam-roles-for-service-accounts/test-deploying-pod-with-aws-access/index.html
  target does not exist --- docs/workshops/iam-roles-for-service-accounts/test-deploying-pod-with-aws-access/index.html --> /images/sample-app-iam-role.png
docs/workshops/iam-roles-for-service-accounts/create-oidc-provider/index.html
  target does not exist --- docs/workshops/iam-roles-for-service-accounts/create-oidc-provider/index.html --> /images/oidc-provider.png
docs/workshops/iam-roles-for-service-accounts/overview/index.html
  target does not exist --- docs/workshops/iam-roles-for-service-accounts/overview/index.html --> /images/irsa-arch.png
```

**Comment by TerryHowe** [comment]
Close this if we cannot get the images

**Comment by TerryHowe** [comment]
Cleaned up and pulled the two commits https://github.com/aws/eks-anywhere/pull/4495 but missing images

**Pull request closed without merging**
