### PR TITLE
Update Nutanix E2E to run tests for different K8S versions

### PR DESCRIPTION
**Pull request by abhinavmpandey08**
*Description of changes:*
Update Nutanix E2E to run tests for different K8S versions
Also enable 1.20-1.22 Simple Flow Nutanix E2E tests

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by mitalipaygude — COMMENTED** [review]
Looks good!

No tests for 1.24 yet?

**Comment by abhinavmpandey08** [comment]
> Looks good!
> 
> No tests for 1.24 yet? Conformance, simple flow or others?

I haven't built the 1.24 images on Nutanix CI environment yet. Once, that is done, I will ask Nutanix folks to add 1.24 tests

**Review by pokearu — APPROVED** [review]

**Pull request merged**
