### PR TITLE
Refactor e2e for vSphere to use table driven tests:

### PR DESCRIPTION
**Pull request by jacobweinstock**
*Issue #, if available:*

*Description of changes:*
This seeks to optimize for readability and less duplication of code. This doesn't give us an increase in the reliability of these tests. Also, this change seeks to teach about table driven testing.

*Testing (if applicable):*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by jaxesn — COMMENTED** [review]
I like this train of thought! Id like to see how this could look across providers... in my simplistic view, ideally we have could have 1 set of tests that we want to run across every provider (providers can and will have their own specific ones too) to ensure that when we add new critical use cases, or even new providers, they are running across all without requiring engineers to remember to add everywhere.

**Comment by jacobweinstock** [comment]
Looks like i have not taken into account how we allocate clusters for testing. Looks like we have tests as single functions so that we can parse them out for properly assigning clusters to tests in a serial way.

https://github.com/aws/eks-anywhere/blob/main/internal/test/e2e/list.go#L14

**Comment by pokearu** [comment]
> Looks like i have not taken into account how we allocate clusters for testing. Looks like we have tests as single functions so that we can parse them out for properly assigning clusters to tests in a serial way. It also allows us to specify tests to skip at runtime. This allows for non code changes to skip tests.
> 
> https://github.com/aws/eks-anywhere/blob/main/internal/test/e2e/list.go#L14

That’s right. I don’t think we can leverage table tests, that would force all the tests to run in a single EC2. We had the tests as individual ones as they can run in parallel in their own environments.

**Comment by jaxesn** [comment]
Let's think of other options though what we have now where we have to rely on keeping things in sync across versions and providers is less than ideal. Just to throw out something wild, what about just auto generating the test files from a known template so at least we could keep them in sync?

**Comment by jacobweinstock** [comment]
I like the wild idea, @jaxesn ! We should discuss more. I found that running or skipping table driven tests (which in pure Go are just sub-tests) is no different than what we currently do. See this link for sub-test running: https://go.dev/blog/subtests
I believe the only thing left to solve, that would allow for table driven tests to be used, is that the way we determine all tests is by using `./bin/e2e.test -test.list` and this doesn't print out sub-tests. I'll keep investigating to see if i can find a solution.

**Pull request closed without merging**
