### PR TITLE
Trigger Prod Bundle Release

### PR DESCRIPTION
**Pull request by cxbrowne1207**
*Issue #, if available:*

*Description of changes:*
Trigger prod bundle release for v0.15.0

*Testing (if applicable):*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by abhay-krishna — APPROVED** [review]

**Comment by cxbrowne1207** [comment]
/override eks-anywhere-cli-attribution-presubmit eks-anywhere-mocks-presubmits eks-anywhere-presubmit

**Comment by cxbrowne1207** [comment]
/override eks-anywhere-cli-attribution-presubmit eks-anywhere-presubmit eks-anywhere-release-tooling-presubmit

**Pull request merged**
