### PR TITLE
Doc change : Add correct url for LICENCE

### PR DESCRIPTION
**Pull request by PankajWorks**
*Issue #, if available:*

*Description of changes:*

LICENCE was pointing to a url which was not available. Corrected the URL.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by abhay-krishna** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/aws/eks-anywhere/pull/599#" title="Author self-approved">PankajWorks</a>*
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **chrisnegus**
You can assign the PR to them by writing `/assign @chrisnegus` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=aws%2Feks-anywhere).

<details open>
Needs approval from an approver in each of these files:

- **[docs/OWNERS](https://github.com/aws/eks-anywhere/blob/main/docs/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by abhay-krishna** [comment]
Hi @PankajWorks. Thanks for your PR.

I'm waiting for a [aws](https://github.com/orgs/aws/people) member to verify that this patch is reasonable to test. If it is, they should reply with `/ok-to-test` on its own line. Until that is done, I will not automatically test new commits in this PR, but the usual testing commands by org members will still work. Regular contributors should [join the org](https://github.com/orgs/aws/people) to skip this step.

Once the patch is verified, the new status will be reflected by the `ok-to-test` label.

I understand the commands that are listed [here](https://go.k8s.io/bot-commands?repo=aws%2Feks-anywhere).

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by abhay-krishna** [comment]
@rothgar: The `/test` command needs one or more targets.
The following commands are available to trigger jobs:
* `/test eks-anywhere-attribution-files-presubmit`
* `/test eks-anywhere-cluster-controller-tooling-presubmit`
* `/test eks-anywhere-docs-presubmit`
* `/test eks-anywhere-e2e-presubmit`
* `/test eks-anywhere-mocks-presubmits`
* `/test eks-anywhere-presubmit`
* `/test eks-anywhere-release-tooling-presubmit`

Use `/test all` to run the following jobs:
* `eks-anywhere-docs-presubmit`



<details>

In response to [this](https://github.com/aws/eks-anywhere/pull/599#issuecomment-962848170):

>/test


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Review by rothgar — APPROVED** [review]

**Comment by abhay-krishna** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/aws/eks-anywhere/pull/599#" title="Author self-approved">PankajWorks</a>*, *<a href="https://github.com/aws/eks-anywhere/pull/599#pullrequestreview-799726194" title="Approved">rothgar</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=aws%2Feks-anywhere).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[docs/OWNERS](https://github.com/aws/eks-anywhere/blob/main/docs/OWNERS)~~ [rothgar]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Pull request merged**
