### PR TITLE
Add support for registry mirror authentication for bottlerocket

### PR DESCRIPTION
**Pull request by ahreehong**
*Issue #, if available:*
#3349

*Description of changes:*

*Testing (if applicable):*
Created baremetal and vsphere clusters using private registry

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by abhinavmpandey08 — APPROVED** [review]
/approve
/lgtm
/woof

**Review by vignesh-goutham — APPROVED** [review]

**Pull request merged**
