### PR TITLE
Add docker workers CAPI spec generator

### PR DESCRIPTION
**Pull request by mitalipaygude**
*Issue #, if available:*

*Description of changes:*
Add docker workers CAPI spec generator
*Testing (if applicable):*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by g-gaston** [comment]
/override "codecov/patch"

The lines not covered are actually very difficult to test and doing so wouldn't provide much value. They will never fail unless there is a programming error (the code changes to something invalid), since they just deal with object init and don't depend on anything external. If the code were to change to something invalid, the other tests that assert for no error will fail, preventing us from shipping a bug.

Given that and since coverage is 75%, overriding.

**Review by cxbrowne1207 — APPROVED** [review]
/lgtm

**Pull request merged**
