### PR TITLE
Updated docs to indicate if unstacked etcd topology is supported

### PR DESCRIPTION
**Pull request by RobertNorthard**
*Issue #, if available:*
N/A

*Description of changes:*
Updated docs to indicate which Amazon EKS Anywhere deployment options do not support the unstacked etcd topology which is recommended.

*Testing (if applicable):*
N/A

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by chrisnegus — COMMENTED** [review]
Looks okay to me, with a very small suggestion. I requested @abhay-krishna to look at it as well.

**Comment by abhay-krishna** [comment]
Thanks for the docs update, @RobertNorthard! Looks good to me, I'll approve after @chrisnegus's comment is addressed.

**Comment by RobertNorthard** [comment]
> Thanks for the docs update, @RobertNorthard! Looks good to me, I'll approve after @chrisnegus's comment is addressed.

Thank you @abhay-krishna for reviewing I've applied the suggested change.

**Pull request merged**
