### PR TITLE
Update reference/config/baremetal.md

### PR DESCRIPTION
**Pull request by d8660091**
Add instruction for setting workerNodeGroupConfigurations to nil

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by cxbrowne1207 — COMMENTED** [review]
Have we made a note somewhere that single node is not supported with Kubernetes version 1.21? Additionally, maybe it would be good to add a version check and error message in the CLI for it as well.

**Comment by d8660091** [comment]
> Have we made a note somewhere that single node is not supported with Kubernetes version 1.21? Additionally, maybe it would be good to add a version check and error message in the CLI for it as well.

Good point. I have added notes for not supporting Kube version <= 1.21 and created a ticket to handle version check.

**Pull request merged**
