### PR TITLE
fix diagnostic bundle collection during delete

### PR DESCRIPTION
**Pull request by danbudris**
*Issue #, if available:*

*Description of changes:*
Diagnostic bundle collection on delete was broken.
We were referencing uninitialized nested unnamed fields, resulting in a nil pointer. 
This will eliminate the nil pointer exception when collecting diagnostic bundles from mgmt clusters during `delete`.

*Testing (if applicable):*
created and deleted a cluster, forcing an error during delete and observing the behavior.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by abhinavmpandey08 — APPROVED** [review]
/lgtm

**Comment by jaxesn** [comment]
can cherry pick this one to 08?

**Pull request merged**
