### PR TITLE
Use control plane and etcd machine configs when building template in controller

### PR DESCRIPTION
**Pull request by vivek-koppuru**
*Issue #, if available:*

*Description of changes:*
Noticed that with recent changes, since we don't have conditions in our template that omits certain `VSphereMachineTemplate` specs if no changes are required there, which is why we used to pass in the older worker specs to the cp and etcd params too. Because of this, updating fields through flux has been failing in our tests as well. This change will retrieve the respective spec and recreate the templates correctly to avoid this issue.

The other solution is to only append the worker node template for flux changes, which would require refactoring the templates more to separate out cp `VSphereMachineTemplate` from objects like `Cluster` as cp always gets appended here: https://github.com/aws/eks-anywhere/blob/main/controllers/controllers/resource/template.go#L80. This is a lesser change until we have separate out the templates more.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by abhay-krishna** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/aws/eks-anywhere/pull/366#" title="Author self-approved">vivek-koppuru</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=aws%2Feks-anywhere).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/aws/eks-anywhere/blob/main/OWNERS)~~ [vivek-koppuru]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by vivek-koppuru** [comment]
/hold

running some tests

**Comment by vivek-koppuru** [comment]
/unhold

finished testing

**Review by abhinavmpandey08 — APPROVED** [review]

**Comment by abhay-krishna** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/aws/eks-anywhere/pull/366#pullrequestreview-769452066" title="Approved">abhinavmpandey08</a>*, *<a href="https://github.com/aws/eks-anywhere/pull/366#" title="Author self-approved">vivek-koppuru</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=aws%2Feks-anywhere).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/aws/eks-anywhere/blob/main/OWNERS)~~ [abhinavmpandey08,vivek-koppuru]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Pull request merged**
