### PR TITLE
Remove kubeVersion argument to bundle reader

### PR DESCRIPTION
**Pull request by ewollesen**
It wasn't being used anywhere anyway.

*Issue #, if available:*

*Description of changes:*

*Testing (if applicable):*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by a-cool-train — CHANGES_REQUESTED** [review]
Both kubeVersion and cliVersion are required to bootstrap eks-anywhere release binary. Please reference this: https://github.com/aws/eks-anywhere/blob/d0a42e7dd823206683983f29049eaaaecaa7f81d/pkg/dependencies/factory.go#L847

**Comment by ewollesen** [comment]
> Both kubeVersion and cliVersion are required to bootstrap eks-anywhere release binary. Please reference this:
> 
> https://github.com/aws/eks-anywhere/blob/d0a42e7dd823206683983f29049eaaaecaa7f81d/pkg/dependencies/factory.go#L847

I respectfully disagree, and here's why:

Excluding tests, the method you've referenced is [called only once](https://github.com/aws/eks-anywhere/blob/d0a42e7dd823206683983f29049eaaaecaa7f81d/cmd/eksctl-anywhere/cmd/common.go#L32):

``` 
func NewDependenciesForPackages(ctx context.Context, opts ...PackageOpt) (*dependencies.Dependencies, error) {
	config := New(opts...)
	return dependencies.NewFactory().
		WithExecutableMountDirs(config.mountPaths...).
		WithExecutableBuilder().
		WithManifestReader().
		WithKubectl().
		WithHelmInsecure().
		WithCuratedPackagesRegistry(config.registryName, config.kubeVersion, version.Get()).
		Build(ctx)
}
```

One can see that the call doesn't use `cliVersion` from the BundleReader, but rather calls `version.Get()` directly. Likewise, the `kubeVersion` is not pulled from BundleReader, but rather it uses the value passed on the command-line directly.

Can you think of other places these might be used? I haven't been able to find any.

**Comment by a-cool-train** [comment]
> > Both kubeVersion and cliVersion are required to bootstrap eks-anywhere release binary. Please reference this:
> > https://github.com/aws/eks-anywhere/blob/d0a42e7dd823206683983f29049eaaaecaa7f81d/pkg/dependencies/factory.go#L847
> 
> I respectfully disagree, and here's why:
> 
> Excluding tests, the method you've referenced is [called only once](https://github.com/aws/eks-anywhere/blob/d0a42e7dd823206683983f29049eaaaecaa7f81d/cmd/eksctl-anywhere/cmd/common.go#L32):
> 
> ```
> func NewDependenciesForPackages(ctx context.Context, opts ...PackageOpt) (*dependencies.Dependencies, error) {
> 	config := New(opts...)
> 	return dependencies.NewFactory().
> 		WithExecutableMountDirs(config.mountPaths...).
> 		WithExecutableBuilder().
> 		WithManifestReader().
> 		WithKubectl().
> 		WithHelmInsecure().
> 		WithCuratedPackagesRegistry(config.registryName, config.kubeVersion, version.Get()).
> 		Build(ctx)
> }
> ```
> 
> One can see that the call doesn't use `cliVersion` from the BundleReader, but rather calls `version.Get()` directly. Likewise, the `kubeVersion` is not pulled from BundleReader, but rather it uses the value passed on the command-line directly.
> 
> Can you think of other places these might be used? I haven't been able to find any.

Here is a reference to the usage: https://github.com/aws/eks-anywhere/blob/dd1d7227035041fbf8cc041947a8143b979717c2/pkg/curatedpackages/defaultregistry.go#L25

**Comment by ewollesen** [comment]
> > > Both kubeVersion and cliVersion are required to bootstrap eks-anywhere release binary. Please reference this:
> > > https://github.com/aws/eks-anywhere/blob/d0a42e7dd823206683983f29049eaaaecaa7f81d/pkg/dependencies/factory.go#L847
> > 
> > 
> > I respectfully disagree, and here's why:
> > Excluding tests, the method you've referenced is [called only once](https://github.com/aws/eks-anywhere/blob/d0a42e7dd823206683983f29049eaaaecaa7f81d/cmd/eksctl-anywhere/cmd/common.go#L32):
> > ```
> > func NewDependenciesForPackages(ctx context.Context, opts ...PackageOpt) (*dependencies.Dependencies, error) {
> > 	config := New(opts...)
> > 	return dependencies.NewFactory().
> > 		WithExecutableMountDirs(config.mountPaths...).
> > 		WithExecutableBuilder().
> > 		WithManifestReader().
> > 		WithKubectl().
> > 		WithHelmInsecure().
> > 		WithCuratedPackagesRegistry(config.registryName, config.kubeVersion, version.Get()).
> > 		Build(ctx)
> > }
> > ```
> >   
> > One can see that the call doesn't use `cliVersion` from the BundleReader, but rather calls `version.Get()` directly. Likewise, the `kubeVersion` is not pulled from BundleReader, but rather it uses the value passed on the command-line directly.
> > Can you think of other places these might be used? I haven't been able to find any.
> 
> Here is a reference to the usage:
> 
> https://github.com/aws/eks-anywhere/blob/dd1d7227035041fbf8cc041947a8143b979717c2/pkg/curatedpackages/defaultregistry.go#L25

I don't see anything related to [BundleReader](https://github.com/aws/eks-anywhere/blob/dd1d7227035041fbf8cc041947a8143b979717c2/pkg/curatedpackages/bundle.go#L30) in that reference. Can you explain your reasoning? All the changes in this PR affect BundleReader only.

That reference does appear to be use pkg/manifests/reader.go's [Reader](https://github.com/aws/eks-anywhere/blob/dd1d7227035041fbf8cc041947a8143b979717c2/pkg/manifests/reader.go#L18) which has similar, but distinct, functionality.

Or am I misunderstanding something?

**Comment by ewollesen** [comment]
Apparently removing code somehow lowers our test coverage?!? I call shenanigans (aka rounding error?) @g-gaston do you know anything about this? I can probably figure out a way to add a test, but I shouldn't have to for this, should I?

**Review by a-cool-train — APPROVED** [review]

**Review by TerryHowe — APPROVED** [review]
/approve

**Pull request merged**
