### PR TITLE
Adding autoscaling annotations to nutanix

### PR DESCRIPTION
**Pull request by junshun**
Adding autoscaling annotations to nutanix to support cluster-autoscaler package

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by jonathanmeier5** [comment]
/lgtm

I defer to @abhinavmpandey08 on nutanix-specific stuff.

**Review by abhinavmpandey08 — APPROVED** [review]
/approve
/lgtm

**Comment by deepakm-ntnx** [comment]
do we need any change in machineDeployment on capx side template https://opendocs.nutanix.com/capx/v1.1.x/experimental/autoscaler/

**Comment by deepakm-ntnx** [comment]
> do we need any change in machineDeployment on capx side template https://opendocs.nutanix.com/capx/v1.1.x/experimental/autoscaler/

nvm, its applied. thanks for fixing this

**Pull request merged**
