### PR TITLE
K8s conformance

### PR DESCRIPTION
**Pull request by TerryHowe**
Create make file to generate K8s conformance PR

### CODE REVIEW

**Review by g-gaston — APPROVED** [review]
Is the idea to run this in any kind of automated way?
I know we have run the conformance tests periodically but not sure if this is an addition or is supposed to replace them.

**Comment by TerryHowe** [comment]
> Is the idea to run this in any kind of automated way? I know we have run the conformance tests periodically but not sure if this is an addition or is supposed to replace them.

This is not for automation, this just allows anyone to create the CNCF certificate PR. This is mostly for me really so I don't have to remember what fields to update in the README and project file.

**Comment by TerryHowe** [comment]
This is just a runbook in code.

**Pull request merged**
