### PR TITLE
Deprecate overrideClusterSpecFile option from cluster config

### PR DESCRIPTION
**Pull request by jiayiwang7**
*Issue #, if available:*

*Description of changes:*

Remove overrideClusterSpec option in cluster config, since we haven't seen real case usage on that feature.
Also giving customers too much control over what CAPI spec they provide tends to cause more issues during create/upgrade.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by g-gaston** [comment]
This technically a backwards breaking change
Tbh I don't think anyone was using it, so as long as we test that the crd can be updated in place and existing objects are still valid, I'm ok with the change
Maybe it's safer to just keep the field in the api, mark it as deprecated and just remove the functionality from the cli. Or even throw an error on if it's specified on create

**Comment by jiayiwang7** [comment]
> This is technically a backwards breaking change
> Tbh I don't think anyone was using it, so as long as we test that the crd can be updated in place and existing objects are still valid, I'm ok with the change
> Maybe it's safer to just keep the field in the api, mark it as deprecated and just remove the functionality from the cli. Or even throw an error on if it's specified on create

good point. added the field back with deprecation warning.

**Review by g-gaston — APPROVED** [review]
thanks!
we should probably mention this is in the changelog

**Review by vivek-koppuru — APPROVED** [review]
/lgtm

**Pull request merged**
