### PR TITLE
Introduce registry mirror InsecureSkipVerify for cloudstack

### PR DESCRIPTION
**Pull request by cxbrowne1207**
*Issue #, if available:*
#1647 following up on the introduction of InsecureSkipVerify flag, and introducing it to the other providers.

*Description of changes:*
This PR adds InsecureSkipVerify option support for Cloudstack.

*Testing (if applicable):*
- Unit testing
- Manual e2e test (registry isn't set up for cloudstack to write an e2e test)

Add the registryMirrorConfiguration property to the cluster spec pointing to the new registry.
```
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: Cluster
metadata:
  name: mgmt
spec:
  ...
  registryMirrorConfiguration:
    endpoint: 1.2.3.4
    port: 5000
    insecureSkipVerify: true
```
Using a bundle-release.yaml with an image of the controller built from the changes in this PR as bundles override, create a cluster.

`bin/eksctl-anywhere import images -i eks-anywhere-images.tar --bundles eks-anywhere-downloads/bundle-release.yaml --registry ${REGISTRY_ENDPOINT}`

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by jiayiwang7 — COMMENTED** [review]
can we add an e2e test?

**Comment by cxbrowne1207** [comment]
> can we add an e2e test?

We dont have registry mirror infra setup for cloudstack yet. The current registry mirror tests are being skipped

**Pull request merged**
