### PR TITLE
Removing clusterID from AWSIamConfig spec and generating uuid

### PR DESCRIPTION
**Pull request by pokearu**
*Description of changes:*
Removing clusterID field from AWSIamConfig CRD. By default the clusterID is set to a UUID during cluster creation and does not support upgrade/gitops to change the value.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by danbudris** [comment]
So, my understanding from the convo the other day is that we'd allow the customer to override the default value if they explicitly wanted to

**Comment by danbudris** [comment]
> So, my understanding from the convo the other day is that we'd allow the users to override the default `clusterId` value if they explicitly wanted to

spoke with @pokearu and we are moving forward with the removal of the clusterID configuration; we can always open up the option to configure it later based on user feedback.

**Comment by pokearu** [comment]
> > So, my understanding from the convo the other day is that we'd allow the users to override the default `clusterId` value if they explicitly wanted to
> 
> spoke with @pokearu and we are moving forward with the removal of the clusterID configuration; we can always open up the option to configure it later based on user feedback.

Yup! Currently we are enforcing a default uuid 👍  and we can address this again based on feedback.

**Review by danbudris — APPROVED** [review]

**Comment by danbudris** [comment]
sorting out integration tests prior to merge

**Pull request merged**
