### PR TITLE
Update Curated Packages documentation to point to latest version

### PR DESCRIPTION
**Pull request by jhaanvi5**
***Description of changes:***
This PR 

- Updates curated packages documentation to point to the latest version. 
- Updates packages command to use `kubectl apply -f packageFileName` instead of `eksctl anywhere apply package -f packageFileName` in the 'Best Practice' section.

***Testing:***
Tested locally using:
```bash
make container-build
make container-serve
```

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by vivek-koppuru — APPROVED** [review]

**Comment by sp1999** [comment]
Merged [#8916](https://github.com/aws/eks-anywhere/pull/8916) to fix above merge conflict while cherry-picking this to `release-0.19` branch

**Pull request merged**
