### PR TITLE
E2E metallb

### PR DESCRIPTION
**Pull request by lewisdiamond**
Add e2e compatible with metallb 0.13.7 (latest release)

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by jonahjon** [comment]
will changing all the `e.cluster` > `e.Cluster` break anything?

**Comment by lewisdiamond** [comment]
> will changing all the `e.cluster` > `e.Cluster` break anything?
If I missed any the e2e would not build. Outside of that I don't see any problem.

**Comment by ivyostosh** [comment]
Many tests failed :(

**Pull request merged**
