### PR TITLE
Trigger staging release

### PR DESCRIPTION
**Pull request by jonahjon**
Signed-off-by: jonahjon <jonahjones094@gmail.com>

*Issue #, if available:*

*Description of changes:*

*Testing (if applicable):*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by TerryHowe** [comment]
presubmit failed

**Comment by jonahjon** [comment]
Looks to be an issue due to a recent cloudtstack PR https://github.com/aws/eks-anywhere-build-tooling/pull/1170

**Review by jaxesn — APPROVED** [review]
/approve

**Pull request merged**
