### PR TITLE
Update cluster-api to v1.4.2

### PR DESCRIPTION
**Pull request by g-gaston**
## Description of changes
This involved updating controller-runtime as well, which required updating rufio and eks-a curated packages.

There were some breaking changes in curated packages, hence all those updates.

@a-cool-train @ivyostosh @jonahjon for visibility on the curated packages changes

@jiayiwang7 for visibility on the snow changes (this are trivial)

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by ivyostosh** [comment]
Regarding changes impacting packages, I've tested eksctl anywhere generate/list/install/apply packages commands and confirmed they are working as expected.

**Review by jiayiwang7 — APPROVED** [review]

**Comment by g-gaston** [comment]
Codecov is not passing. But the areas where we are lacking coverage are only related with the curated packages commands, and those were manually tested by Ivy (thanks again!)

So merging this.

**Pull request merged**
