### PR TITLE
First draft of management cluster getting started guide (#573)

### PR DESCRIPTION
**Pull request by chrisnegus**
Cherry pick of [PR 573](https://github.com/aws/eks-anywhere/pull/573) to add the new getting started procedure to v0.6.0 from main.

### CODE REVIEW

**Comment by abhay-krishna** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/aws/eks-anywhere/pull/621#" title="Author self-approved">chrisnegus</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=aws%2Feks-anywhere).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[docs/OWNERS](https://github.com/aws/eks-anywhere/blob/v0.6.0/docs/OWNERS)~~ [chrisnegus]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by abhay-krishna** [comment]
@chrisnegus: The following test **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
eks-anywhere-docs-presubmit | c850beea8629d5516199eb8528ee2873ae973fea | [link](https://prow.eks.amazonaws.com/view/s3/prowpresubmitsdataclusterstack-prowbucket7c73355c-vfwwxd2eb4gp/pr-logs/pull/aws_eks-anywhere/621/eks-anywhere-docs-presubmit/1458628160676433920) | `/test eks-anywhere-docs-presubmit`

[Full PR test history](https://prow.eks.amazonaws.com/pr-history?org=aws&repo=eks-anywhere&pr=621). [Your PR dashboard](https://prow.eks.amazonaws.com/pr?query=is:pr+state:open+author:chrisnegus).

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by abhay-krishna** [comment]
@chrisnegus: The following test **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
eks-anywhere-docs-presubmit | c850beea8629d5516199eb8528ee2873ae973fea | [link](https://prow.eks.amazonaws.com/view/s3/prowpresubmitsdataclusterstack-prowbucket7c73355c-vfwwxd2eb4gp/pr-logs/pull/aws_eks-anywhere/621/eks-anywhere-docs-presubmit/1458644926240657408) | `/test eks-anywhere-docs-presubmit`

[Full PR test history](https://prow.eks.amazonaws.com/pr-history?org=aws&repo=eks-anywhere&pr=621). [Your PR dashboard](https://prow.eks.amazonaws.com/pr?query=is:pr+state:open+author:chrisnegus).

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by chrisnegus** [comment]
Apparently this merge is failing because of a problem with prow. It merged fine into main. I will follow up on working through this issue.

**Review by vivek-koppuru — APPROVED** [review]
/lgtm

**Pull request merged**
