### PR TITLE
Remove unnecessary fetchs from tinkerbell template

### PR DESCRIPTION
**Pull request by g-gaston**
*Issue #, if available:*

*Description of changes:*
The versions bundle is already included in the `cluster.Spec`

*Testing (if applicable):*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by d8660091** [comment]
/lgtm
nit: cover the added line with unit test

**Review by pokearu — APPROVED** [review]
Changes look good.

The `GetVersionsBundleForVersion` was initially needed elsewhere in the generate cluster config for Tinkerbell but we don't need that now after this #2243.

**Pull request merged**
