### PR TITLE
Multiclusters E2E test framework

### PR DESCRIPTION
**Pull request by g-gaston**
*Description of changes:*
First take for adapting our e2e test framework to management+workload clusters
The changes are lengthy but super super simple, I recommend going commit by commit, that will make the review way easier

Some ideas:
* This uses the same patterns and syntax that we are used to for self managed clusters, but applied to multicluster tests.
  * Management and workload clusters are defined the same way.
  * Operations over clusters syntax is the same (`CreateCluster` `DeleteCluster`, etc.).
  * All the code to validate single cluster tests will work here as well, hopefully transparently
  * This should make writing new tests for workload clusters almost a copy paste excercise
* A multicluster test allows for one management cluster and multiple workload clusters

I added a "demo" test, so it's easier to see how the framework can be used. I'm not sure this test in particular is the most valuable one, but I think it demonstrates how any other test can be build. It can be removed once other better tests are added.

I can't guarantee that all the other testing tooling (Flux, upgrades, oidc, etc.) will work out of the box (there might be parts that were written making very specific assumptions about single cluster tests), but most of it should. I only need to make minimal modifications to the existing code to make the create-delete flow work.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by abhay-krishna** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/aws/eks-anywhere/pull/579#" title="Author self-approved">g-gaston</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=aws%2Feks-anywhere).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/aws/eks-anywhere/blob/main/OWNERS)~~ [g-gaston]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by mdsgabriel — APPROVED** [review]

**Comment by abhay-krishna** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/aws/eks-anywhere/pull/579#" title="Author self-approved">g-gaston</a>*, *<a href="https://github.com/aws/eks-anywhere/pull/579#pullrequestreview-798296811" title="Approved">mdsgabriel</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=aws%2Feks-anywhere).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/aws/eks-anywhere/blob/main/OWNERS)~~ [g-gaston,mdsgabriel]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Pull request merged**
