### PR TITLE
Initial styling changes

### PR DESCRIPTION
**Pull request by markapruett**
*Issue #, if available:*
https://github.com/aws/eks-anywhere/issues/2242

*Description of changes:*
First group of changes to new docs styling. [Mocks](https://www.figma.com/file/ZnMmXsSjDJFwDEcWjrEO8T/eks_a_doc?node-id=70%3A1085)

[Hosted Amplify url](https://main.d1r10vimdgysy2.amplifyapp.com/)

Note: not all images and spacing are done yet. Working with designer to get the rest of these in a follow up release.

*Testing (if applicable):*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by chrisnegus — COMMENTED** [review]
You did really well matching the design from the UX team. One difference is that the logo is written as "EKS Anywhere" in the UX design and as EKS ANYWHERE currently. I think the mixed case would be better. That logo seems to come from the existing design. Is there a reason it can't be mixed case?

**Comment by TerryHowe** [comment]
My only comment here is can you fork the repo next time so we don't get dev branches on the main repo

**Comment by markapruett** [comment]
@TerryHowe @chrisnegus I forked and created a new PR to align with our branching strategy. New PR link: https://github.com/aws/eks-anywhere/pull/2273

**Comment by chrisnegus** [comment]
Okay. I'll take a look at that.

**Pull request closed without merging**
