### PR TITLE
Upload EKS-A tarballs before running tests

### PR DESCRIPTION
**Pull request by abhay-krishna**
Same as #3040.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by jaxesn — APPROVED** [review]

**Comment by abhay-krishna** [comment]
/override eks-anywhere-e2e-presubmit
/override eks-anywhere-mocks-presubmits
/override eks-anywhere-presubmit

These changes are not being tested by these presubmits.

**Pull request merged**
